import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.backends.backend_pdf import PdfPages

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
PIPELINE_CSV = os.path.join(BASE_DIR, 'analytics_pipeline_output.csv')
RAW_CSV = os.path.join(BASE_DIR, 'raw_wearable_data.csv')
OUTPUT_PDF = os.path.join(BASE_DIR, 'user_report.pdf')

# Load data
pipeline = pd.read_csv(PIPELINE_CSV, parse_dates=['date'])
if os.path.exists(RAW_CSV):
    raw = pd.read_csv(RAW_CSV, parse_dates=['timestamp'])
else:
    raw = None

# Guard for empty
if pipeline.empty:
    raise SystemExit('No pipeline data found for report generation.')

# Summary metrics
pipeline['date_str'] = pipeline['date'].dt.strftime('%b %d, %Y')
period = f"{pipeline['date'].min().strftime('%b %d, %Y')} - {pipeline['date'].max().strftime('%b %d, %Y')}"

summary = {
    'Period': period,
    'Days analyzed': len(pipeline),
    'Avg readiness': f"{pipeline['readiness_score'].mean():.1f}",
    'High readiness days': int((pipeline['readiness_label'] == 'high').sum()),
    'Optimal recovery days': int((pipeline['recovery_state'] == 'optimal').sum()),
    'Injury events': int(pipeline['injury_event'].sum()),
    'High injury risk days': int((pipeline['injury_risk_label'] == 'high').sum()),
}

# Plot style
plt.style.use('bmh')  # Professional style

with PdfPages(OUTPUT_PDF) as pdf:
    # Page 1: Professional title page
    fig, ax = plt.subplots(figsize=(11, 8.5))
    ax.axis('off')
    # Background gradient effect
    ax.add_patch(plt.Rectangle((0,0),1,1,transform=ax.transAxes, color='#f8f9fa', zorder=-1))
    ax.add_patch(plt.Rectangle((0,0.7),1,0.3,transform=ax.transAxes, color='#007bff', alpha=0.1, zorder=-1))
    
    ax.text(0.5, 0.85, 'Athlete Wellness Analytics', ha='center', va='center', fontsize=28, fontweight='bold', color='#2c3e50')
    ax.text(0.5, 0.75, 'Executive Report', ha='center', va='center', fontsize=24, color='#34495e')
    ax.text(0.5, 0.65, f'Analysis Period: {summary["Period"]}', ha='center', va='center', fontsize=16, color='#7f8c8d')
    
    # Summary box
    ax.add_patch(plt.Rectangle((0.1,0.1),0.8,0.5, facecolor='white', edgecolor='#bdc3c7', linewidth=2))
    ax.text(0.5, 0.55, 'Key Metrics Summary', ha='center', va='center', fontsize=18, fontweight='bold', color='#2c3e50')
    
    y_pos = 0.45
    for line in [
        f'Total Days Analyzed: {summary["Days analyzed"]}',
        f'Average Readiness Score: {summary["Avg readiness"]}/100',
        f'High Readiness Days: {summary["High readiness days"]}',
        f'Optimal Recovery Days: {summary["Optimal recovery days"]}',
        f'Injury Events: {summary["Injury events"]}',
        f'High Injury Risk Days: {summary["High injury risk days"]}',
    ]:
        ax.text(0.15, y_pos, f'• {line}', fontsize=12, color='#34495e')
        y_pos -= 0.05
    
    ax.text(0.5, 0.05, 'Generated by MoodChanger Analytics Pipeline', ha='center', va='center', fontsize=10, color='#95a5a6')
    pdf.savefig(fig, bbox_inches='tight')
    plt.close(fig)

    # Page 2: Readiness trend with enhanced styling
    fig, ax = plt.subplots(figsize=(11, 8.5))
    ax.plot(pipeline['date'], pipeline['readiness_score'], color='#3498db', linewidth=3, label='Daily Readiness', marker='o', markersize=4, markerfacecolor='white', markeredgecolor='#3498db')
    ax.plot(pipeline['date'], pipeline['readiness_score'].rolling(7, min_periods=1).mean(), color='#e74c3c', linewidth=2, linestyle='--', label='7-day Trend')
    ax.axhline(75, color='#27ae60', linestyle='-', linewidth=2, label='High Threshold (75)')
    ax.axhline(50, color='#f39c12', linestyle='-', linewidth=2, label='Moderate Threshold (50)')
    ax.fill_between(pipeline['date'], pipeline['readiness_score'], alpha=0.1, color='#3498db')
    ax.set_title('Readiness Score Trend', fontsize=20, fontweight='bold', color='#2c3e50', pad=20)
    ax.set_xlabel('Date', fontsize=14)
    ax.set_ylabel('Readiness Score (0-100)', fontsize=14)
    ax.set_ylim(0, 110)
    ax.legend(loc='upper left', fontsize=12, frameon=True, facecolor='white', edgecolor='#bdc3c7')
    ax.grid(True, alpha=0.3, color='#bdc3c7')
    ax.text(0.02, 0.95, 'Interpretation: Monitor downward trends as potential injury signals', transform=ax.transAxes, fontsize=11, bbox=dict(boxstyle="round,pad=0.3", facecolor="#ecf0f1", edgecolor="#bdc3c7"))
    pdf.savefig(fig, bbox_inches='tight')
    plt.close(fig)

    # Page 3: ACWR timeline with enhanced styling
    fig, ax = plt.subplots(figsize=(11, 8.5))
    ax.plot(pipeline['date'], pipeline['acwr'], color='#e67e22', linewidth=3, label='ACWR', marker='s', markersize=4, markerfacecolor='white', markeredgecolor='#e67e22')
    ax.axhline(0.8, color='#3498db', linestyle='-', linewidth=2, label='Undertraining (0.8)')
    ax.axhline(1.3, color='#27ae60', linestyle='-', linewidth=2, label='Optimal Upper (1.3)')
    ax.axhline(1.5, color='#e74c3c', linestyle='-', linewidth=2, label='Overreaching (1.5)')
    ax.fill_between(pipeline['date'], pipeline['acwr'], 1.3, where=(pipeline['acwr'] > 1.3), color='#e74c3c', alpha=0.2, label='High Risk Zone')
    ax.set_title('Acute:Chronic Workload Ratio (ACWR)', fontsize=20, fontweight='bold', color='#2c3e50', pad=20)
    ax.set_ylabel('ACWR', fontsize=14)
    ax.set_xlabel('Date', fontsize=14)
    ax.legend(loc='upper left', fontsize=12, frameon=True, facecolor='white', edgecolor='#bdc3c7')
    ax.grid(True, alpha=0.3, color='#bdc3c7')
    ax.text(0.02, 0.95, 'Interpretation: Sustained 0.8-1.3 is optimal; >1.5 indicates overreaching risk', transform=ax.transAxes, fontsize=11, bbox=dict(boxstyle="round,pad=0.3", facecolor="#ecf0f1", edgecolor="#bdc3c7"))
    pdf.savefig(fig, bbox_inches='tight')
    plt.close(fig)

    # Page 4: Injury risk + scatter with enhanced styling
    fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(11, 11), sharex=True)
    ax1.bar(pipeline['date'], pipeline['injury_risk_score'], color='#e74c3c', alpha=0.7, edgecolor='#c0392b', linewidth=0.5)
    ax1.set_title('Injury Risk Score Timeline', fontsize=18, fontweight='bold', color='#2c3e50', pad=15)
    ax1.set_ylabel('Risk Score (0-100)', fontsize=14)
    ax1.axhline(60, color='#c0392b', linestyle='-', linewidth=2, label='High Risk (60)')
    ax1.axhline(30, color='#f39c12', linestyle='-', linewidth=2, label='Moderate Risk (30)')
    ax1.legend(loc='upper left', fontsize=12, frameon=True, facecolor='white', edgecolor='#bdc3c7')
    ax1.grid(True, alpha=0.3, color='#bdc3c7')

    sc = ax2.scatter(pipeline['acwr'], pipeline['soreness_score'], c=pipeline['injury_risk_score'], cmap='RdYlGn_r', s=70, edgecolors='#34495e', alpha=0.85)
    ax2.set_title('ACWR vs Soreness Score Correlation', fontsize=18, fontweight='bold', color='#2c3e50', pad=15)
    ax2.set_xlabel('ACWR', fontsize=14)
    ax2.set_ylabel('Soreness (1-10)', fontsize=14)
    cbar = fig.colorbar(sc, ax=ax2, shrink=0.8)
    cbar.set_label('Injury Risk Score', fontsize=12)
    ax2.grid(True, alpha=0.3, color='#bdc3c7')
    ax2.text(0.02, 0.95, 'Interpretation: Higher ACWR and soreness correlate with increased injury risk', transform=ax2.transAxes, fontsize=11, bbox=dict(boxstyle="round,pad=0.3", facecolor="#ecf0f1", edgecolor="#bdc3c7"))
    pdf.savefig(fig, bbox_inches='tight')
    plt.close(fig)

    # Additional page: Raw sensor day if available
    if raw is not None and not raw.empty:
        daily = raw.copy()
        day = daily['timestamp'].dt.date.unique()[-1]
        sample = daily[daily['timestamp'].dt.date == day]
        if not sample.empty:
            fig, axs = plt.subplots(3, 1, figsize=(11, 11), sharex=True)
            axs[0].plot(sample['timestamp'], sample['HR_bpm'], color='#fb923c', linewidth=1)
            axs[0].set_title(f'Raw HR signal for {day}')
            axs[0].set_ylabel('HR (bpm)')
            axs[1].plot(sample['timestamp'], sample['HRV_ms'], color='#818cf8', linewidth=1)
            axs[1].set_title('Raw HRV signal')
            axs[1].set_ylabel('HRV (ms)')
            axs[2].plot(sample['timestamp'], sample['accel_g'], color='#22c55e', linewidth=1, label='Accel (g)')
            axs[2].plot(sample['timestamp'], sample['skin_temp_C'], color='#f472b6', linewidth=1, label='Skin Temp (°C)')
            axs[2].set_title('Raw Accel & Temp')
            axs[2].set_ylabel('Accel / Temp')
            axs[2].legend()
            pdf.savefig(fig, bbox_inches='tight')
            plt.close(fig)

print(f'Report saved to: {OUTPUT_PDF}')
