import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.backends.backend_pdf import PdfPages

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
PIPELINE_CSV = os.path.join(BASE_DIR, 'analytics_pipeline_output.csv')
RAW_CSV = os.path.join(BASE_DIR, 'raw_wearable_data.csv')
OUTPUT_PDF = os.path.join(BASE_DIR, 'user_report.pdf')

# Load data
pipeline = pd.read_csv(PIPELINE_CSV, parse_dates=['date'])
if os.path.exists(RAW_CSV):
    raw = pd.read_csv(RAW_CSV, parse_dates=['timestamp'])
else:
    raw = None

# Guard for empty
if pipeline.empty:
    raise SystemExit('No pipeline data found for report generation.')

# Summary metrics
pipeline['date_str'] = pipeline['date'].dt.strftime('%b %d, %Y')
period = f"{pipeline['date'].min().strftime('%b %d, %Y')} - {pipeline['date'].max().strftime('%b %d, %Y')}"

summary = {
    'Period': period,
    'Days analyzed': len(pipeline),
    'Avg readiness': f"{pipeline['readiness_score'].mean():.1f}",
    'High readiness days': int((pipeline['readiness_label'] == 'high').sum()),
    'Optimal recovery days': int((pipeline['recovery_state'] == 'optimal').sum()),
    'Injury events': int(pipeline['injury_event'].sum()),
    'High injury risk days': int((pipeline['injury_risk_label'] == 'high').sum()),
}

# Plot style
plt.style.use('ggplot')

with PdfPages(OUTPUT_PDF) as pdf:
    # Page 1: title + summary
    fig, ax = plt.subplots(figsize=(11, 8.5))
    ax.axis('off')
    ax.set_title('Athlete Wellness & Mood Analytics Report', fontsize=20, weight='bold', pad=20)
    ax.text(0.05, 0.82, 'Source project: MoodChanger-main', fontsize=12)
    ax.text(0.05, 0.78, f'Date range: {summary["Period"]}', fontsize=12)
    ax.text(0.05, 0.74, f'Total days: {summary["Days analyzed"]}', fontsize=12)
    ax.text(0.05, 0.70, 'Summary metrics:', fontsize=14, weight='bold')

    y = 0.66
    for k, v in summary.items():
        if k in ('Period', 'Days analyzed'): continue
        ax.text(0.08, y, f'- {k}: {v}', fontsize=12)
        y -= 0.04

    ax.text(0.05, 0.20, 'Generated by: generate_report.py in MoodChanger-main', fontsize=10, color='gray')
    pdf.savefig(fig, bbox_inches='tight')
    plt.close(fig)

    # Page 2: Readiness trend
    fig, ax = plt.subplots(figsize=(11, 8.5))
    ax.plot(pipeline['date'], pipeline['readiness_score'], color='#38bdf8', linewidth=2, label='Readiness Score')
    ax.plot(pipeline['date'], pipeline['readiness_score'].rolling(7, min_periods=1).mean(), color='white', linewidth=1.3, linestyle='--', label='7d mean')
    ax.axhline(75, color='#22c55e', linestyle='--', alpha=0.6, label='High (75)')
    ax.axhline(50, color='#f59e0b', linestyle='--', alpha=0.6, label='Moderate (50)')
    ax.set_title('Readiness Score Trend', fontsize=16)
    ax.set_ylabel('Score')
    ax.set_xlabel('Date')
    ax.legend()
    pdf.savefig(fig, bbox_inches='tight')
    plt.close(fig)

    # Page 3: ACWR timeline
    fig, ax = plt.subplots(figsize=(11, 8.5))
    ax.plot(pipeline['date'], pipeline['acwr'], color='#fb923c', linewidth=2, label='ACWR')
    ax.axhline(0.8, color='#60a5fa', linestyle='--', alpha=0.6)
    ax.axhline(1.3, color='#22c55e', linestyle='--', alpha=0.6)
    ax.axhline(1.5, color='#f59e0b', linestyle='--', alpha=0.6)
    ax.set_title('Acute:Chronic Workload Ratio (ACWR)', fontsize=16)
    ax.set_ylabel('ACWR')
    ax.set_xlabel('Date')
    ax.legend()
    pdf.savefig(fig, bbox_inches='tight')
    plt.close(fig)

    # Page 4: Injury risk + scatter
    fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(11, 11), sharex=True)
    ax1.bar(pipeline['date'], pipeline['injury_risk_score'], color='#ef4444', alpha=0.6)
    ax1.set_title('Injury Risk Score Timeline', fontsize=16)
    ax1.set_ylabel('Risk Score')
    ax1.axhline(60, color='red', linestyle='--', alpha=0.6)
    ax1.axhline(30, color='orange', linestyle='--', alpha=0.6)

    sc = ax2.scatter(pipeline['acwr'], pipeline['soreness_score'], c=pipeline['injury_risk_score'], cmap='coolwarm', s=50)
    ax2.set_title('ACWR vs Soreness Score', fontsize=16)
    ax2.set_xlabel('ACWR')
    ax2.set_ylabel('Soreness (1-10)')
    cbar = fig.colorbar(sc, ax=ax2)
    cbar.set_label('Injury Risk Score')

    pdf.savefig(fig, bbox_inches='tight')
    plt.close(fig)

    # Additional page: Raw sensor day if available
    if raw is not None and not raw.empty:
        daily = raw.copy()
        day = daily['timestamp'].dt.date.unique()[-1]
        sample = daily[daily['timestamp'].dt.date == day]
        if not sample.empty:
            fig, axs = plt.subplots(3, 1, figsize=(11, 11), sharex=True)
            axs[0].plot(sample['timestamp'], sample['HR_bpm'], color='#fb923c', linewidth=1)
            axs[0].set_title(f'Raw HR signal for {day}')
            axs[0].set_ylabel('HR (bpm)')
            axs[1].plot(sample['timestamp'], sample['HRV_ms'], color='#818cf8', linewidth=1)
            axs[1].set_title('Raw HRV signal')
            axs[1].set_ylabel('HRV (ms)')
            axs[2].plot(sample['timestamp'], sample['accel_g'], color='#22c55e', linewidth=1, label='Accel (g)')
            axs[2].plot(sample['timestamp'], sample['skin_temp_C'], color='#f472b6', linewidth=1, label='Skin Temp (°C)')
            axs[2].set_title('Raw Accel & Temp')
            axs[2].set_ylabel('Accel / Temp')
            axs[2].legend()
            pdf.savefig(fig, bbox_inches='tight')
            plt.close(fig)

print(f'Report saved to: {OUTPUT_PDF}')
